site_name: Drakes
theme: readthedocs 
repo_url: https://github.com/shakna-israel/drakes
site_description: Suzie Drakes has never been a normal kid, but her time with ASIO puts that all in the past.
site_author: shakna-israel 
use_directory_urls: true 
nav:
 - Home: index.md
 - License: LICENSE.md
 - Contributing: CONTRIBUTING.md
 - Drakes: Drakes.md
 - Drakes - The Five Eyes: Drakes2.md
